# Generated by Django 3.2.21 on 2023-10-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='seller',
        ),
    ]
