# Generated by Django 3.2.21 on 2023-11-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verification',
            field=models.BooleanField(default=False),
        ),
    ]
