# Generated by Django 3.2.21 on 2023-11-21 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20231121_2328'),
        ('shop', '0034_auto_20231121_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='shops',
            field=models.ManyToManyField(related_name='accounts', through='shop.AccountShops', to='shop.Shop', verbose_name='Магазины'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
