# Generated by Django 3.2.21 on 2023-11-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_phone_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(unique=True, verbose_name='Телефон'),
        ),
    ]
