# Generated by Django 3.2.21 on 2023-11-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20231121_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='postal_code',
            field=models.CharField(max_length=100, verbose_name='Почтовый индекс'),
        ),
    ]
