# Generated by Django 3.2.21 on 2023-11-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_phone'),
        ('accounts', '0012_user_is_superuser'),
    ]

    operations = [
    ]
