# Generated by Django 3.2.21 on 2024-01-10 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20231208_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bin',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,12}$', 'Только цифры, максимум 12.')], verbose_name='БИН'),
        ),
        migrations.AddField(
            model_name='user',
            name='iin',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,12}$', 'Только цифры, максимум 12.')], verbose_name='ИИН'),
        ),
    ]
