# Generated by Django 3.2.21 on 2024-01-11 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20240111_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iin_bin',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,12}$', 'Только цифры, максимум 12.')], verbose_name='ИИН/БИН'),
        ),
    ]
