version: '3'

# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  app:
    container_name: django-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: bash -c "python manage.py makemigrations --merge --noinput &&
                      python manage.py migrate --noinput &&
                      python manage.py runserver 0.0.0.0:8000"


  redis:
     container_name: redis
     image: redis:5.0.1

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A core.celery worker -l info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Asia/Almaty

  celery-beat:
    container_name: celery-beat
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A core.celery beat -l info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Asia/Almaty


  # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./static:/usr/share/nginx/html/static:ro
  #   depends_on:
  #     - app

networks:
  default:
    external: True
    name: default_net

