version: '3'

services:
  kaspi:
    container_name: kaspixml
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5050:5050'
    env_file:
      - .env
    volumes:
      - .:/usr/src/kaspi
    command: bash -c "python3 main.py"


networks:
  default:
    external: True
    name: default_net
