# Generated by Django 3.2.21 on 2023-10-13 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название магазина')),
                ('logo', models.ImageField(null=True, upload_to='logos/', verbose_name='Логотип магазина')),
                ('description', models.TextField(max_length=2500, null=True, verbose_name='Описание магазина')),
                ('theme', models.CharField(choices=[('Dark', 'Темная'), ('Light', 'Светлая'), ('Red', 'Красная')], default='Dark', max_length=255, verbose_name='Тема магазина')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
