# Generated by Django 3.2.21 on 2023-10-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_shop_shopmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='logo',
            field=models.ImageField(default='default_img/default', null=True, upload_to='logos/', verbose_name='Логотип магазина'),
        ),
    ]
