# Generated by Django 3.2.21 on 2023-10-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shopmodel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='Описание магазина'),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='logo',
            field=models.ImageField(blank=True, default='default_img/default', null=True, upload_to='logos/', verbose_name='Логотип магазина'),
        ),
    ]
