# Generated by Django 3.2.21 on 2023-10-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20231013_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название магазина'),
        ),
    ]
