# Generated by Django 3.2.21 on 2023-10-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_shopmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('vendor_code', models.IntegerField(unique=True, verbose_name='Код Поставщика')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка')),
                ('photo_one', models.ImageField(upload_to='product_photos/')),
                ('photo_two', models.ImageField(upload_to='product_photos/')),
                ('photo_three', models.ImageField(upload_to='product_photos/')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shopmodel')),
            ],
        ),
    ]