# Generated by Django 3.2.21 on 2023-10-20 12:58


# Generated by Django 3.2.21 on 2023-10-17 10:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ShopModel',
            new_name='Shop',
        ),
    ]