# Generated by Django 3.2.21 on 2023-10-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20231017_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_one',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_three',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_two',
        ),
    ]
