# Generated by Django 3.2.21 on 2023-10-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_shop_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
