# Generated by Django 3.2.21 on 2023-10-21 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20231021_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timediscount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_discount', to='shop.product'),
        ),
    ]
