# Generated by Django 3.2.21 on 2023-10-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_timediscount_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timediscount',
            name='discount',
        ),
        migrations.AddField(
            model_name='timediscount',
            name='discount_in_percent',
            field=models.PositiveIntegerField(default=78),
            preserve_default=False,
        ),
    ]
