# Generated by Django 3.2.21 on 2023-10-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20231021_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timediscount',
            old_name='discount_in_percent',
            new_name='discount',
        ),
    ]
