# Generated by Django 3.2.21 on 2023-10-25 12:32

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('shop', '0019_auto_20231023_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='products', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэги'),
        ),
    ]
