# Generated by Django 3.2.21 on 2023-11-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_bucket_ip_address'),
    ]

    operations = [
    ]
