# Generated by Django 3.2.21 on 2023-11-01 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0025_alter_bucket_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Цена со скдикой'),
        ),
        migrations.AddField(
            model_name='timediscount',
            name='discount_in_currency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='theme',
            field=models.CharField(choices=[('black', 'Темная'), ('white', 'Светлая'), ('blue', 'Синяя')], default='black', max_length=255, verbose_name='Тема магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='Владелец магазина'),
        ),
        migrations.AlterField(
            model_name='timediscount',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
