# Generated by Django 3.2.21 on 2023-11-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_merge_20231103_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
