# Generated by Django 3.2.21 on 2023-12-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCityShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_city', to='shop.city')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.CharField(max_length=150, verbose_name='ID партнера')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_city_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_product', to='shop.partnercityshop')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_product', to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='partnercityshop',
            name='partner_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_city', to='shop.partnershop'),
        ),
    ]
