# Generated by Django 3.2.21 on 2023-11-13 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0029_auto_20231113_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='payer_address',
            field=models.CharField(default='asdasd', max_length=250, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payer_city',
            field=models.CharField(default='sadasdasd', max_length=100, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payer_email',
            field=models.EmailField(default='adssdasdasd', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payer_name',
            field=models.CharField(default='adasdasdad', max_length=150, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payer_phone',
            field=models.CharField(default='awdawdad', max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payer_postal_code',
            field=models.CharField(default='awadwawdadw', max_length=20, verbose_name='Почтовый индекс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payer_surname',
            field=models.CharField(default='awdawdawd', max_length=150, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
