# Generated by Django 3.2.21 on 2023-12-04 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20231204_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnercityshop',
            name='partner_shop',
        ),
        migrations.RemoveField(
            model_name='partnerproduct',
            name='partner_city_shop',
        ),
        migrations.AddField(
            model_name='partnercityshop',
            name='partner_product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='partner_city', to='shop.partnerproduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerproduct',
            name='partner_shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='partner_product', to='shop.partnershop'),
            preserve_default=False,
        ),
    ]
