# Generated by Django 3.2.21 on 2023-12-06 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20231204_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerproduct',
            name='city',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='partner_product', to='shop.city'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PartnerCityShop',
        ),
    ]
