# Generated by Django 3.2.21 on 2023-11-13 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20231113_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='shop.shop'),
            preserve_default=False,
        ),
    ]
