# Generated by Django 3.2.21 on 2023-12-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20231206_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershop',
            name='partner_id',
            field=models.IntegerField(verbose_name='ID партнера'),
        ),
    ]
