# Generated by Django 3.2.21 on 2023-11-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_bucket_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='unit_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Цена за единицу'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='price_per_product',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
