# Generated by Django 3.2.21 on 2023-12-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_partnershop_partner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='partner_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Партнера(Kaspi)'),
        ),
    ]
