# Generated by Django 3.2.21 on 2023-12-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_shop_partner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='tg_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Телеграм-токен'),
        ),
    ]
