# Generated by Django 3.2.21 on 2023-11-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20231121_2328'),
        ('shop', '0033_auto_20231117_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket_user', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.account'),
        ),
        migrations.CreateModel(
            name='AccountShops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_account', to='accounts.account')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_shops', to='shop.shop')),
            ],
        ),
    ]
