# Generated by Django 3.2.21 on 2023-11-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20231121_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payer',
            new_name='account',
        ),
        migrations.AddField(
            model_name='order',
            name='user_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IP плательщика'),
        ),
    ]
