# Generated by Django 3.2.21 on 2023-12-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
    ]
