# Generated by Django 3.2.21 on 2024-01-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_alter_shop_options'),
        ('shop', '0038_merge_0034_shop_tg_token_0037_alter_order_date'),
    ]

    operations = [
    ]
