# Generated by Django 3.2.21 on 2023-12-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_merge_20231227_1816'),
        ('shop', '0039_merge_20231228_1320'),
    ]

    operations = [
    ]
