# Generated by Django 3.2.21 on 2024-01-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_merge_20240105_1940'),
        ('shop', '0040_merge_20231228_1410'),
    ]

    operations = [
    ]
